name: Build OBS Scene Tree Folder

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout plugin code
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.24.0'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.*'
          host: windows
          target: desktop
          arch: win64_msvc2019_64

      - name: Checkout OBS Studio
        uses: actions/checkout@v4
        with:
          repository: obsproject/obs-studio
          ref: 29.1.3   # stabile OBS-Version, kannst du ändern
          path: obs-studio

      - name: Configure OBS Studio
        run: cmake -S obs-studio -B obs-build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DDISABLE_UI=ON

      - name: Build OBS Studio (libobs only)
        run: cmake --build obs-build --config Release --target libobs

      - name: Configure plugin
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="%Qt6_DIR%;${{ github.workspace }}/obs-build"

      - name: Build plugin
        run: cmake --build build --config Release

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: scene-tree-folder-dll
          path: build/Release/*.dll
