name: Build OBS Scene Tree Folder

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.2'
          arch: 'win64_msvc2019_64'

      - name: Download OBS dependencies
        run: |
          curl -L -o obs-deps.zip https://github.com/obsproject/obs-deps/releases/download/2024-06-18/win64-deps-2024-06-18.zip
          7z x obs-deps.zip -oobs-deps

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }};${{ github.workspace }}/obs-deps"

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: obs-scene-tree-folder
          path: build/Release/*.dll
