name: Build OBS Scene Tree

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install -y cmake ninja git

      - name: Download OBS Studio SDK
        run: |
          git clone --branch 32.0.1 --depth=1 https://github.com/obsproject/obs-studio.git
          mkdir obs-build
          cd obs-build
          cmake -DENABLE_UI=OFF -DENABLE_SCRIPTING=OFF -DENABLE_PIPEWIRE=OFF -DENABLE_VST=OFF -DCMAKE_INSTALL_PREFIX=../obs-install ../obs-studio -G "Ninja"
          cmake --build . --target install --config Release
          cd ..

      - name: Configure plugin build
        run: |
          mkdir build
          cd build
          cmake -DLIBOBS_INCLUDE_DIR="../obs-install/include" -DLIBOBS_LIB="../obs-install/lib/obs.lib" ..
      
      - name: Build plugin
        run: |
          cd build
          cmake --build . --config Release
