name: Build OBS Scene Tree View

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@v3.27.7

      - name: Download OBS Plugin SDK (31.0.0)
        run: |
          curl -L -o obs-dev.zip https://github.com/obsproject/obs-studio/releases/download/31.0.0/obs-studio-dev-31.0.0-windows.zip
          mkdir obs-sdk
          7z x obs-dev.zip -oobs-sdk

      - name: Configure CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="${{ github.workspace }}\obs-sdk"

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: obs-scene-tree-view
          path: build/Release/*.dll
