name: Build OBS Scene Tree Folder

on:
  workflow_dispatch:   # manuell starten
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.24.0'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Configure project
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build project
        run: cmake --build build --config Release

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: scene-tree-folder-dll
          path: build/Release/*.dll
